#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'Gesture-Commands','console_scripts','Command_Gesture'
__requires__ = 'Gesture-Commands'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('Gesture-Commands', 'console_scripts', 'Command_Gesture')()
    )
